### ISSUE TITLE
Space inserted when <app> occurs in a part of a compound only

### ISSUE THREAD

**Issue by ppasedach** [chchch/upama#38]
In [Śivasaṃhitā 2.25](https://muk.li/upama/sivasamhita:2:ss-2-kd) there is a variant for a member (_iḍā_) of a compound (_iḍānāmnī_) only. I have not managed to encode that without a a space being added after the lemma, e.g. `<app><lem>iḍā</lem><rdg wit="#KD-I">raṃḍā</rdg></app><pc> </pc>nāmnī` gives me a space. I fear that is a design decision, that lemmas always have to be words?

**Comment by chchch** [comment]
Hmm... not sure why I did that, but I pushed a fix! Let me know if that fix makes other things look weird...

**Comment by ppasedach** [comment]
Yes, that mostly fixed it, thanks. Something funny still appears though when I switch to another witness, and collate against this one. `KD: iḍā°nāmnī` (Strangely that degree circle disappeared when I copied and pasted it here, so I had to add it again manually.) https://muk.li/upama/sivasamhita:2:ss-2-p?upama_ver=h1g7vm2lbu .

**Comment by chchch** [comment]
Oh I think it's because you're using `<pc> </pc>` to break the compound in the edition... you can probably just get rid of it, it should collate nicely without it.
